name: 'Setup .NET Core SDK'

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: 'Setup .NET Core SDK'
      uses: actions/setup-dotnet@v4.0.0
      with:
        dotnet-version: 8.0.x
